// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBufS5n2UjIYivw-3BVNC_t2bTtAyeCoY',
    appId: '1:209065904592:android:d77121224db666b15c91d5',
    messagingSenderId: '209065904592',
    projectId: 'travel-dating-app',
    storageBucket: 'travel-dating-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGuJa9ix3hpeChEq2xDwEdi_-2UwjK-DA',
    appId: '1:209065904592:ios:c52936ac9f37da815c91d5',
    messagingSenderId: '209065904592',
    projectId: 'travel-dating-app',
    storageBucket: 'travel-dating-app.appspot.com',
    androidClientId: '209065904592-gi5da28d0oalortb5cm74a8u6pnhao1u.apps.googleusercontent.com',
    iosClientId: '209065904592-i53ke4l97vhn6vehmumsvl2bovurshvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelDatingApp',
  );

}